base:
  project: category-prediction-project
  random_state: 42
  target_col: category
  categorical_cols: product_name brand_name

data_source:
  source: data_given/

load_data:
  raw_dataset_csv: data/raw/combinedcategory.csv

transformed_data:
  final_dataframe: data/processed/finaldataframe.csv
  translated_dataframe: data/processed/translated_dataframe.csv
  # change this to 50
  filter_count: 0


model_parameters:
  bert_model_name: bert-base-uncased
  max_length: 128
  batch_size: 16
  epochs: 4
  learning_rate: 2e-5
  test_size: 0.2
  random_state: 42
  shuffle: True

model_dir: saved_models
pred_dir:  prediction_service/model/

reports:
  scores: reports/scores.json
  files: reports/files/unique_category.json
  translated_data: reports/files/
  final_category: reports/files/final_category.json
  plots: reports/figures/

webapp_model_dir: prediction_service/model/model.pth
num_labels: 25
id2label: {0: 'Household', 1: 'Dairy', 2: 'galletas', 3: 'Beverages', 4: 'Meat/Poultry/Seafood', 5: 'bombones', 6: 'Other', 7: 'AlcoholicBeverages', 8: 'Snacks/Candy', 9: 'Canned/JarredGoods', 10: 'PersonalCare', 11: 'FrozenFoods', 12: 'Pasta/Grains', 13: 'Bakery', 14: 'Prepared/Ready-Made Foods', 15: 'Toys: Other', 16: 'Prepared/Ready-Made_Foods', 17: 'Electronics', 18: 'Baby', 19: 'Pet', 20: 'FreshProduce', 21: 'Toys', 22: 'Produce', 23: 'Vitamins: Other', 24: 'Medicines: Household'}

open_ai_model: gpt-3.5-turbo

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: BERTModel
  run_name: categoryPrediction
  registered_model_name: BERTmodel
  remote_server_uri: http://localhost:1234