version: '3.9'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./copywritingAgent:/code/copywritingAgent
    command: uvicorn copywritingAgent.main:app --host 0.0.0.0 --port 8000
